name: Daily Update

on:
  schedule:
    # Run every day at midnight EST
    - cron: '0 5 * * *' # GitHub Actions uses UTC, so 5 AM UTC is midnight EST
  workflow_dispatch: # Allows manual trigger of the workflow if needed

jobs:
  update_csvs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update.py
        run: python update.py

      - name: Check for changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Daily CSV update"
            git push
          else
            echo "No changes to commit."
