name: Update and Commit CSVs

on:
  schedule:
    - cron: '0 5 * * *' # 12am ET
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update.py
        run: python update.py

      - name: List files in data directory
        run: ls -la data

      - name: Check Git status
        run: git status

      - name: Commit and push changes
        run: |
          git add data/
          git commit -m "Update CSVs via GitHub Actions" || echo "No changes to commit"
          git push